# Generated by Django 5.2 on 2025-07-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_list', '0003_tasks_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_done',
            field=models.BooleanField(null=True),
        ),
    ]
