# Generated by Django 5.2 on 2025-07-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_list', '0004_tasks_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Tasks', 'verbose_name_plural': 'Tasks'},
        ),
    ]
